#!/bin/bash
set -eu

VERSION=5.2.26
VERSION_MINOR=${VERSION%.*}
VERSION_MAJOR=${VERSION%%.*}

for ALT_TAG in {latest,$VERSION,$VERSION_MINOR,$VERSION_MAJOR}; do
  docker tag \
    "${IMAGE_NAME}" \
    "${DOCKER_REPO}:${ALT_TAG}"
  docker push \
    "${DOCKER_REPO}:${ALT_TAG}"
done