#!/bin/bash
set -eu

. "$(readlink -m ${BASH_SOURCE[@]}/../../VERSION)"

BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
VCS_URL=$(git config --get remote.origin.url)
VCS_REF=$(git rev-parse --short HEAD)

docker build \
  --build-arg FLAVOUR=$DOCKER_TAG \
  --build-arg PDNS_VERSION=$VERSION \
  --build-arg REVISION=$REVISION \
  --build-arg VCS_URL=$VCS_URL \
  --build-arg VCS_REF=$VCS_REF \
  --build-arg BUILD_DATE=$BUILD_DATE \
  -t $IMAGE_NAME \
  .
