#!/bin/bash
set -eu

BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
VCS_URL=$(git config --get remote.origin.url)
VCS_REF=$(git rev-parse --short HEAD)
VERSION=1.6.8-2

docker build \
  --build-arg VERSION=$VERSION \
  --build-arg VCS_URL=$VCS_URL \
  --build-arg VCS_REF=$VCS_REF \
  --build-arg BUILD_DATE=$BUILD_DATE \
  -t $IMAGE_NAME \
  .