#!/bin/bash
set -eu

. "$(readlink -m ${BASH_SOURCE[@]}/../../VERSION)"

docker tag \
  "${IMAGE_NAME}" \
  "${DOCKER_REPO}:${VERSION}-${DOCKER_TAG}"
docker push \
  "${DOCKER_REPO}:${VERSION}-${DOCKER_TAG}"
